### ISSUE TITLE
Error While running eval_model.py to caption images.

### ISSUE THREAD

**Issue by islamshahil** [Div99/Image-Captioning#12]
After excuting: prepare_data.py and train_model.py while I was trying to run eval_model.py on few images to find caption, I received the below Error:
```
Traceback (most recent call last):
  File "eval_model.py", line 127, in <module>
    model = load_model(filename)
  File "./.env/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 206, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects,
  File "./.env/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 182, in load_model_from_hdf5
    model_config = json_utils.decode(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by islamshahil** [comment]
Solved this by downgrading h5yp to 2.10.0
