### ISSUE TITLE
VGG16 Error "AttributeError: 'Tensor' object has no attribute '_keras_shape'"

### ISSUE THREAD

**Issue by TestPW** [Div99/Image-Captioning#3]
When I am running command `python prepare_data.py` getting below error

Using TensorFlow backend.
Traceback (most recent call last):
  File "prepare_data.py", line 132, in <module>
    features = extract_features(directory)
  File "prepare_data.py", line 38, in extract_features
    model = Model(inputs=model.inputs, outputs=model.layers[-1].output)
  File "C:\Users\XX\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\XX\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\network.py", line 91, in __init__
    self._init_graph_network(*args, **kwargs)
  File "C:\Users\XX\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\network.py", line 251, in _init_graph_network
    input_shapes=[x._keras_shape for x in self.inputs],
  File "C:\Users\XX\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\network.py", line 251, in <listcomp>
    input_shapes=[x._keras_shape for x in self.inputs],
AttributeError: 'Tensor' object has no attribute '_keras_shape'

**Comment by Div99** [comment]
It seems to be an error with Keras itself. Probably has to do with them changing their Model API. Will take a look
